/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.mobi_29thjune_prod.myjavaservice1.controller;

import com.mobi_29thjune_prod.myjavaservice1.MyJavaService2;
import java.lang.String;
import javax.servlet.http.HttpServletRequest;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;

@RestController
@RequestMapping(value = "/myJavaService2")
public class MyJavaService2Controller {

    @Autowired
    private MyJavaService2 myJavaService2;

    @RequestMapping(value = "/sampleJavaOperation", produces = "application/json", method = RequestMethod.GET)
    public String sampleJavaOperation(@RequestParam(value = "name", required = false) String name, HttpServletRequest request) {
        return myJavaService2.sampleJavaOperation(name, request);
    }
}
