/*Generated by WaveMaker Studio*/

package com.mobi_29thjune_prod.db123testing.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


public interface DB123TestingProcedureExecutorService {


}


