/*Generated by WaveMaker Studio*/

package com.mobi_29thjune_prod.db123testing.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.mobi_29thjune_prod.db123testing.models.query.InsertQueryRequest;

public interface DB123TestingQueryExecutorService {

    Integer executeInsert_query(InsertQueryRequest insertQueryRequest);

}


