/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

package com.mobi_29thjune_prod.services.calculator1.services;
import com.mobi_29thjune_prod.services.calculator1.*;
import java.util.List;

import com.wavemaker.runtime.soap.util.SoapSettingsResolver;
import com.wavemaker.runtime.soap.SoapServiceSettings;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import javax.xml.ws.BindingProvider;



@Service
public class Calculator1Service{

    @Autowired
    @Qualifier("Calculator1SoapServiceSettings")
    private SoapServiceSettings soapServiceSettings;


	public DivideResponse divide(  com.mobi_29thjune_prod.services.calculator1.Divide parameters )
	          {
 	    Calculator calculator = new Calculator();
 ICalculator icalculator = calculator.getICalculator();
 SoapSettingsResolver.setBindingProperties((BindingProvider)icalculator, soapServiceSettings);
 return icalculator.divide(parameters );
	}

	public SubtractResponse subtract(  com.mobi_29thjune_prod.services.calculator1.Subtract parameters )
	          {
 	    Calculator calculator = new Calculator();
 ICalculator icalculator = calculator.getICalculator();
 SoapSettingsResolver.setBindingProperties((BindingProvider)icalculator, soapServiceSettings);
 return icalculator.subtract(parameters );
	}

	public MultiplyResponse multiply(  com.mobi_29thjune_prod.services.calculator1.Multiply parameters )
	          {
 	    Calculator calculator = new Calculator();
 ICalculator icalculator = calculator.getICalculator();
 SoapSettingsResolver.setBindingProperties((BindingProvider)icalculator, soapServiceSettings);
 return icalculator.multiply(parameters );
	}

	public AddResponse add(  com.mobi_29thjune_prod.services.calculator1.Add parameters )
	          {
 	    Calculator calculator = new Calculator();
 ICalculator icalculator = calculator.getICalculator();
 SoapSettingsResolver.setBindingProperties((BindingProvider)icalculator, soapServiceSettings);
 return icalculator.add(parameters );
	}
}
