/*Generated by WaveMaker Studio*/
@javax.xml.bind.annotation.XmlSchema(namespace = "http://tempuri.org/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mobi_29thjune_prod.services.calculator;
