/*Generated by WaveMaker Studio*/

package com.mobi_29thjune_prod.db123testing.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import com.wavemaker.commons.wrapper.IntegerWrapper;
import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.mobi_29thjune_prod.db123testing.models.query.InsertQueryRequest;
import com.mobi_29thjune_prod.db123testing.service.DB123TestingQueryExecutorService;

@RestController(value = "DB123Testing.QueryExecutionController")
@RequestMapping("/DB123Testing/queryExecutor")
@Api(value = "QueryExecutionController", description = "controller class for query execution")
public class QueryExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(QueryExecutionController.class);

    @Autowired
    private DB123TestingQueryExecutorService queryService;

    @RequestMapping(value = "/queries/insert_query", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "insert_query")
    public IntegerWrapper executeInsert_query(@Valid @RequestPart("wm_data_json") InsertQueryRequest insertQueryRequest, @RequestPart(value = "Icon") MultipartFile icon, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: insert_query");
        insertQueryRequest.setIcon(WMMultipartUtils.toByteArray(icon));
        Integer _result = queryService.executeInsert_query(insertQueryRequest);
        LOGGER.debug("got the result for named query: insert_query, result:{}", _result);
        return new IntegerWrapper(_result);
    }

}


