/*Generated by WaveMaker Studio*/
package com.mobi_29thjune_prod.services.calculator1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2017-07-25T10:12:43.848Z
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.parasoft.com/wsdl/calculator/", name = "ICalculator")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ICalculator {

    @WebResult(name = "divideResponse", targetNamespace = "http://www.parasoft.com/wsdl/calculator/", partName = "parameters")
    @WebMethod(action = "divide")
    public DivideResponse divide(
        @WebParam(partName = "parameters", name = "divide", targetNamespace = "http://www.parasoft.com/wsdl/calculator/")
        Divide parameters
    );

    @WebResult(name = "subtractResponse", targetNamespace = "http://www.parasoft.com/wsdl/calculator/", partName = "parameters")
    @WebMethod(action = "subtract")
    public SubtractResponse subtract(
        @WebParam(partName = "parameters", name = "subtract", targetNamespace = "http://www.parasoft.com/wsdl/calculator/")
        Subtract parameters
    );

    @WebResult(name = "multiplyResponse", targetNamespace = "http://www.parasoft.com/wsdl/calculator/", partName = "parameters")
    @WebMethod(action = "multiply")
    public MultiplyResponse multiply(
        @WebParam(partName = "parameters", name = "multiply", targetNamespace = "http://www.parasoft.com/wsdl/calculator/")
        Multiply parameters
    );

    @WebResult(name = "addResponse", targetNamespace = "http://www.parasoft.com/wsdl/calculator/", partName = "parameters")
    @WebMethod(action = "add")
    public AddResponse add(
        @WebParam(partName = "parameters", name = "add", targetNamespace = "http://www.parasoft.com/wsdl/calculator/")
        Add parameters
    );
}
