/*Generated by WaveMaker Studio*/
package com.mobi_29thjune_prod.test_notables.dao;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.orm.hibernate4.HibernateTemplate;
import org.springframework.stereotype.Repository;

import com.wavemaker.runtime.data.dao.WMGenericDaoImpl;

import com.mobi_29thjune_prod.test_notables.Table2;

/**
 * Specifies methods used to obtain and modify Table2 related information
 * which is stored in the database.
 */
@Repository("test_notables.Table2Dao")
public class Table2Dao extends WMGenericDaoImpl<Table2, Integer> {

    @Autowired
    @Qualifier("test_notablesTemplate")
    private HibernateTemplate template;

    public HibernateTemplate getTemplate() {
        return this.template;
    }
}

